name: AHK Release
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with AHK v2
        uses: benmusson/ahk2exe-action@v1
        with:
          in: DolphinScoreboardSync.ahk
          out: DolphinScoreboardSync.exe
          ahk-tag: v2.0.11

      - name: Create Release Bundle
        shell: pwsh
        run: |
          # Create a directory for the bundle
          New-Item -ItemType Directory -Path "DolphinSync-Windows-v1"
          
          # Copy files into the bundle
          Copy-Item "DolphinScoreboardSync.exe" "DolphinSync-Windows-v1/"
          Copy-Item "config.json.example" "DolphinSync-Windows-v1/"
          Copy-Item "ReleaseInstructions.txt" "DolphinSync-Windows-v1/README.txt"
          
          # Zip the bundle
          Compress-Archive -Path "DolphinSync-Windows-v1/*" -DestinationPath "DolphinScoreboardSync-Windows.zip"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DolphinScoreboardSync-ZIP
          path: DolphinScoreboardSync-Windows.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: DolphinScoreboardSync-Windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
