name: Windows Check
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  win-check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Windows Check Passed"
